### ISSUE TITLE
Lets build this together!

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/pymail-io#1]
I need your help to build PyMail IO ... please create issues , pull requests ... let's build this amazing library together!

**Comment by E-RROR** [comment]
Can I Help You ?? : - )

**Comment by E-RROR** [comment]
Nowadays I Have Reall Problem to sending emails in python... I'll be happy to help you with this;

**Comment by joegasewicz** [comment]
Thats amazing @E-RROR :o)
I'll post up a manifest as an issue this evening and then you can add to it & or open more issues. This library is going to be designed to interface with https://github.com/joegasewicz/pytask_io - the goal is that we won't need to use celery anymore. So we probably need to get that working first as a simple server and then we can import it into this project as a dependency...  let me know your thoughts @E-RROR thank you. Joe.

**Comment by joegasewicz** [comment]
> Can I Help You ?? : - )

Yes! In fact im going to start work on the asynio  mail server first -https://github.com/joegasewicz/pytask_io

Its up to you whether you want to join me working on PyTask-IO first or start work here on PyMail-IO..

**Comment by E-RROR** [comment]
> > Can I Help You ?? : - )
> 
> Yes! In fact im going to start work on the asynio mail server first -https://github.com/joegasewicz/pytask_io
> 
> Its up to you whether you want to join me working on PyTask-IO first or start work here on PyMail-IO..

I Will Help You With PyTask io... Just If I Have a Social or Messanger Link to Speak With You About That is Cool ; )

**Comment by joegasewicz** [comment]
> > > Can I Help You ?? : - )
> > 
> > 
> > Yes! In fact im going to start work on the asynio mail server first -https://github.com/joegasewicz/pytask_io
> > Its up to you whether you want to join me working on PyTask-IO first or start work here on PyMail-IO..
> 
> I Will Help You With PyTask io... Just If I Have a Social or Messanger Link to Speak With You About That is Cool ; )

I use viber, if you email me on joegasewicz@gmail.com & send me your number I can send you an invite, thank you. Joe
